apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: flex-auditlogging
  namespace: flex
  labels:
    team: flex
  annotations:
    dcat.data.nav.no/title: "flex.auditlogging"
    dcat.data.nav.no/description: "Topic for flex auditlogging"
spec:
  pool: {{kafkaPool}}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 3
    replication: 3
    retentionBytes: -1    # Messages will never get deleted because of disk space
    retentionHours: 6576  # Messages are stored for 6 months
  acl:
    - team: flex
      application: sykepengesoknad-backend
      access: readwrite
    - team: flex
      application: flex-auditlogging
      access: readwrite
