/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo1.maven.org/maven2/")
    }

    maven {
        url = uri("https://github-package-registry-mirror.gc.nav.no/cached/maven-release")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.io.github.microutils.kotlin.logging.jvm)
    api(libs.ch.qos.logback.logback.classic)
    api(libs.net.logstash.logback.logstash.logback.encoder)
    api(libs.io.ktor.ktor.server.core.jvm)
    api(libs.io.ktor.ktor.server.netty.jvm)
    api(libs.org.apache.kafka.kafka.clients)
    api(libs.com.fasterxml.jackson.module.jackson.module.kotlin)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310)
    api(libs.no.nav.common.audit.log)
    testImplementation(libs.org.jetbrains.kotlin.kotlin.test.junit5)
}

group = "no.nav.arbeidsgiver"
version = "1.0-SNAPSHOT"
description = "consoleApp"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
