azureTenant: trygdeetaten.no
kafkaPool: nav-dev
environment: dev
db_tier: db-f1-micro
db_size: 10
db_highAvailability: false
db_pointInTimeRecovery: false
cpu: 300m
memory: 250Mi
replicas_min: 1
replicas_max: 1
env: