azureTenant: nav.no
kafkaPool: nav-prod
environment: prod
db_tier: db-custom-4-15360
db_size: 250
db_highAvailability: true
db_pointInTimeRecovery: true
cpu: 1000m
memory: 2048Mi
replicas_min: 0
replicas_max: 0
env: