aiven-kafka:
  auto-offset-reset: none

no.nav.security.jwt:
  issuer:
    azureator:
      discoveryurl: http://localhost:${mock-oauth2-server.port}/azureator/.well-known/openid-configuration
      accepted_audience: syfosoknad-client-id
    tokenx:
      discoveryurl: http://localhost:${mock-oauth2-server.port}/tokenx/.well-known/openid-configuration
      accepted_audience: sykepengesoknad-backend-client-id
